// Auto-generated by compile_shaders.py
#pragma once
#include <cstdint>
#include <unordered_map>
#include <string>

namespace Shape::Renderer::Vulkan::EmbeddedShaders {

struct ShaderModule {
    const uint8_t* bytecode;
    size_t size;
};

inline const std::unordered_map<std::string, ShaderModule>& GetAll() {
    static const std::unordered_map<std::string, ShaderModule> shaders;
    return shaders;
}

} // namespace Shape::Renderer::Vulkan::EmbeddedShaders
