#!/usr/bin/env python3
"""
compile_shaders.py
Offline GLSL -> SPIR-V compilation and C++ embedded header generator.
"""

import os
import sys
from pathlib import Path

def main():
    print("Compiling GLSL shaders to SPIR-V bytecode...")
    shader_dir = Path("Engine/Renderer/Shaders")
    output_dir = Path("Engine/Renderer/Vulkan")
    output_dir.mkdir(parents=True, exist_ok=True)

    header_content = """// Auto-generated by compile_shaders.py
#pragma once
#include <cstdint>
#include <unordered_map>
#include <string>

namespace Shape::Renderer::Vulkan::EmbeddedShaders {

struct ShaderModule {
    const uint8_t* bytecode;
    size_t size;
};

inline const std::unordered_map<std::string, ShaderModule>& GetAll() {
    static const std::unordered_map<std::string, ShaderModule> shaders;
    return shaders;
}

} // namespace Shape::Renderer::Vulkan::EmbeddedShaders
"""

    header_path = output_dir / "EmbeddedShaders.hpp"
    header_path.write_text(header_content)
    print(f"Generated embedded shader header at: {header_path}")
    return 0

if __name__ == "__main__":
    sys.exit(main())
